#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Folder }}'

[[blocks]]
  type = 'rprompt'
  overflow = "hide"

  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = "p:white"
    background = "transparent"
    template = " {{ .FormattedMs }} "

    [blocks.segments.properties]
      style = "austin"
      always_enabled = true

  [[blocks.segments]]
    type = "time"
    style = "plain"
    # Follows the following syntax: https://ohmyposh.dev/docs/segments/time#syntax
    template = "@ {{ .CurrentDate | date \"Jan-2-06 3:04:05 PM\" }}"

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    foreground = 'p:white'
    background = 'transparent'
    template = '  {{ .PWD }} '

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = 'p:black'
    foreground_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}',
      '{{ if gt .Ahead 0 }}p:white{{ end }}'
    ]
    background = 'green'
    background_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}magenta{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}',
      '{{ if gt .Ahead 0 }}#49416D{{ end }}',
      '{{ if gt .Behind 0 }}#7A306C{{ end }}'
    ]
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }} '

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true
      branch_icon = ''


[[blocks]]
  type = 'prompt'
  newline = true
  alignment = "left"

  [[blocks.segments]]
    type = 'text'
    style = "plain"
    template = " ❯"
    foreground = 'white'

[secondary_prompt]
  foreground = 'p:black'
  background = 'transparent'
  template = '<,p:green> ❯ </> '

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'
